mypjt/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/',views.login, name='login'),
    path('logout/',views.logout,name='logout'),
    path('signup/',views.signup, name='signup'),
    path('delete/',views.delete,name='delete'),
    path('update/',views.update,name='update'),
    path('password/',views.change_password,name='change_password'),

]

mypjt/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name ='index'),
    path('<int:pk>/',views.detail , name='detail'),
    path('create/',views.create, name='create'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]








mypjt/mypjt/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
]

mypjt/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass

mypjt/movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=20)
    description = models.TextField()
    

mypjt/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

class CustomUserCreationForm(UserCreationForm):
    # email =forms.EmailField(label="이메일")
    class Meta(UserCreationForm.Meta):
        model =get_user_model()


class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('first_name','last_name')

mypjt/movies/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'

mypjt/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.views.decorators.http import require_POST,require_http_methods

@require_http_methods(["GET", "POST"])
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('movies:index')
 
    else :
        form = AuthenticationForm()
    context = {'form' : form,}
    return render(request,'accounts/login.html',context)

@require_POST
def logout(request):
    auth_logout(request)
    return redirect('movies:index')

@require_http_methods(["GET", "POST"])
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('movies:index')
    else:
        form = CustomUserCreationForm()
    context = {'form': form, }
    return render(request,'accounts/signup.html',context)

@require_http_methods(["GET", "POST"])
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance = request.user)
        if form.is_valid():
            form.save()
            return redirect('movies:index')
    else:
        form = CustomUserChangeForm()
    context = {'form': form, }
    return render(request,'accounts/update.html',context)

@require_http_methods(["GET", "POST"])
def change_password(request): 
    if request.method=='POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request,form.user)
            return redirect('movies:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form':form,
    }
    return render(request, 'accounts/change_password.html',context)

@require_POST
def delete(request):
    request.user.delete()   #회원탈퇴
    auth_logout(request)    #로그아웃
    return redirect('movies:index')

mypjt/movies/views.py
from django.shortcuts import render, redirect
from .forms import MovieForm
from .models import Movie
from django.views.decorators.http import require_POST,require_GET,require_http_methods
# Create your views here.
@require_GET
def index(request):
    movies = Movie.objects.all()
    context ={
        'movies':movies
    }
    return render(request, 'movies/index.html',context)

@require_GET
def detail(request,pk):
    movie = Movie.objects.get(pk=pk)
    context ={
        'movie' :movie
    }
    return render(request, 'movies/detail.html',context)

@require_http_methods(["GET", "POST"])
def create(request):
    if request.method =='POST':
        form =MovieForm(request.POST)
        if form.is_valid():
            movie=form.save()
            return redirect('movies:detail',movie.pk)
    else:
        form= MovieForm()
        context = {
            'form' : form
        }
        return render(request, 'movies/create.html',context)
    
@require_http_methods(["GET", "POST"])
def update(request,pk):
    movie = Movie.objects.get(pk=pk)
    if request.method =="POST":
        form = MovieForm(request.POST ,  instance=movie)
        if form.is_valid:
            form.save()
            return redirect('movies:detail', movie.pk)

    else:
        form = MovieForm(instance=movie)
    context ={
        'movie' : movie,
        'form' : form
    }
    return render(request, 'movies/update.html',context)


@require_POST
def delete(request,pk):
    movie = Movie.objects.get(pk=pk)
    movie.delete()
    return redirect('movies:index')

mypjt/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% block content %}
<h1>비밀번호 변경</h1>
<form action="{% url 'accounts:change_password' %}" method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="Submit" />
</form>

{% endblock content %}

mypjt/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
<h1>Login</h1>
<form action="{% url 'accounts:login' %}" method ='POST'>
{% csrf_token %}
{{form.as_p}}
<input type="submit" name="submit" id="">
</form>
{% endblock content %}


mypjt/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
<h1>회원가입</h1>
<form action="{% url 'accounts:signup' %}" method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="Submit" />
</form>

{% endblock content %}

mypjt/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% block content %}
<h1>회원정보수정</h1>
<form action="{% url 'accounts:signup' %}" method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="Submit" />
</form>

{% endblock content %}

mypjt/movies/templates/movies/create.html
{% extends 'base.html' %}

{% block content %}
<h1>CREATE</h1>
<hr>
<form action="{% url 'movies:create'  %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>
<hr>
<a href="{% url 'movies:index' %}">BACK</a>
{% endblock content %}
 

mypjt/movies/templates/movies/detail.html
{% extends 'base.html' %}
{% block content %}
<h1>DETAIL</h1>
<hr>
<p>{{movie.title}}</p>
<p>{{movie.description}}</p>
<br>
<a href="{% url 'movies:update' movie.pk %}">UPDATE</a><br>
<a href="{% url 'movies:delete' movie.pk %}"><input type="submit" value="DELETE"></a><br>
<a href="{% url 'movies:index' %}">BACK</a>
{% endblock content %}



mypjt/movies/templates/movies/index.html
{% extends 'base.html' %}
{% block content %}
<h1>INDEX</h1>

<a href="{% url 'movies:create' %} ">[CREATE]</a>
<hr>

{% for movie in movies  %}
<a href="{% url 'movies:detail' movie.pk %}">{{movie.title}}</a><br>
{% endfor %}


{% endblock content %}

mypjt/movies/templates/movies/update.html
{% extends 'base.html' %}

{% block content %}
<h1>UPDATE</h1>
<hr>
<form action="{% url 'movies:update' movie.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="reset" value="Reset">
    <input type="submit" value="Submit">
</form>
<hr>
<a href="{% url 'movies:detail' movie.pk %}">BACK</a>
{% endblock content %}
 

mypjt/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if user.is_authenticated %}
    <h1>Hello, {{user}}</h1>
    <a href=" {% url 'accounts:update' %}">회원정보수정</a><br>
    <form action="{% url 'accounts:logout' %}" method ="POST">
        {% csrf_token %}<input type="submit" value='logout'></form>
    <form action="{% url 'accounts:delete' %}" method ="POST">
        {% csrf_token %}<input type="submit" value='회원탈퇴'></form>
    <hr>
    {% else %}
    <a href="{% url 'accounts:login' %}">Login</a>
    <a href="{% url 'accounts:signup' %}">Signup</a><hr>
    {% endif %}
  


    {% block content %}
    {% endblock content %}
</body>
</html>